import type { Project } from '../../types'
import { colorRuns, describeColor, normalizeRowColors } from '../colors'
import { sourceCols } from '../grid'
import { emitPlannedPatterns, planPatterns, playedFrames } from './designs'
import { emitConstants, emitEngine, emitSetup, frameBytes, patternBytes } from './engine'
import { buildSteps, emitPlayer, emitTables, emitTypes, engineNeeds } from './loop'
import { has, NO_PASSES, PASS_META, type CodegenOptions } from './options'

export const BOARD_SRAM = { Uno: 2048, Nano: 2048, Leonardo: 2560, Mega: 8192 } as const

export type SramEstimate = {
  /** frameBuffer + pattern, bit-packed. */
  arrayBytes: number
  fitsUno: boolean
  fitsMega: boolean
  recommendedFree: number
}

/**
 * Pointer, rows, cols, stride and the mirror flag — what reading patterns
 * straight out of PROGMEM costs instead of a whole second buffer.
 *
 * Six bytes of fields, plus one of padding: the pointer wants two-byte
 * alignment and the five single bytes around it leave a hole. Seven is what
 * avr-gcc actually reports, on 8x32, 16x48, 20x48 half-width and 12x30 alike.
 */
export const PATTERN_DESCRIPTOR_BYTES = 7

export function estimateSram(
  rows: number,
  cols: number,
  halfWidth = false,
  options: CodegenOptions = NO_PASSES,
): SramEstimate {
  const patternCols = halfWidth ? Math.floor(cols / 2) : cols
  // One bit per LED: ceil(cols / 8) bytes per row, for each buffer that exists.
  const patternRam = has(options, 'progmemPatternRead')
    ? PATTERN_DESCRIPTOR_BYTES
    : rows * Math.ceil(patternCols / 8)
  const arrayBytes = rows * Math.ceil(cols / 8) + patternRam
  const recommendedFree = 300
  return {
    arrayBytes,
    fitsUno: arrayBytes + recommendedFree <= BOARD_SRAM.Uno,
    fitsMega: arrayBytes + recommendedFree <= BOARD_SRAM.Mega,
    recommendedFree,
  }
}

export function sketchName(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, '_').replace(/^_+|_+$/g, '')
  return cleaned || 'LedPattern'
}

/**
 * The panel is monochrome per LED, so row colours are an assembly note: which
 * LED goes on which row. Only printed when the board is not all one colour.
 */
function colorNote(project: Project): string[] {
  const runs = colorRuns(normalizeRowColors(project.rowColors, project.grid.rows))
  if (runs.length < 2) return []
  return [
    ` *`,
    ` * LED colours fitted per row (row 1 first):`,
    ...runs.map((run) =>
      run.from === run.to
        ? ` *   row ${run.from + 1}: ${describeColor(run.hex)}`
        : ` *   rows ${run.from + 1}-${run.to + 1}: ${describeColor(run.hex)}`,
    ),
  ]
}

/**
 * Records which passes shaped this sketch, so a downloaded .ino says how it was
 * built. With no passes enabled this prints nothing and the banner is unchanged.
 */
function optimizationNote(options: CodegenOptions): string[] {
  if (options.passes.size === 0) return []
  const labels = [...options.passes].map((pass) => PASS_META[pass].label)
  return [` *`, ` * Optimised for low memory:`, ...labels.map((l) => ` *   ${l}`)]
}

/**
 * Transistor drivers flip the logic levels the sketch clocks out, so a build
 * that has them says so up front — flashed onto a board wired without them, the
 * panel shows the inverse. Direct drive prints nothing.
 */
function driverNote(project: Project): string[] {
  const { columnDriver, rowDriver } = project.hardware
  const lines: string[] = []
  if (columnDriver === 'pnp') {
    lines.push(` *   Columns: PNP high-side transistors — column bits are clocked inverted (LOW = lit).`)
  }
  if (rowDriver === 'npn') {
    lines.push(` *   Rows: NPN low-side transistors — row select is active-high.`)
  }
  return lines.length ? [` *`, ` * Transistor drivers fitted:`, ...lines] : []
}

function banner(project: Project, options: CodegenOptions): string {
  const { rows, cols, halfWidth } = project.grid
  const sram = estimateSram(rows, cols, halfWidth, options)
  return [
    `/*`,
    ` * ${project.name} — ${rows} x ${cols} LED matrix`,
    ` * Generated by LED Pattern Generator.`,
    ` *`,
    ` * Two 74HC595 chains share one latch: the first shifts ${cols} column bits per row,`,
    ` * the second selects one of ${rows} rows. refreshPanel() multiplexes them.`,
    ` *`,
    ...(has(options, 'progmemPatternRead')
      ? [` * Frames are stored one bit per LED and patterns are read from PROGMEM as`]
      : [` * Frames are stored one bit per LED and patterns live in PROGMEM, so the two`]),
    ` * ${has(options, 'progmemPatternRead') ? 'they play, so the panel buffer costs' : 'buffers cost'} ${sram.arrayBytes} bytes of SRAM${
      sram.fitsUno ? '' : ' — too large for an Uno/Nano (2048 B), use a Mega'
    }.`,
    ...(halfWidth
      ? [` * Patterns are stored ${Math.floor(cols / 2)} columns wide and repeated or mirrored.`]
      : []),
    ...optimizationNote(options),
    ...driverNote(project),
    ...colorNote(project),
    ` */`,
  ].join('\n')
}

export type GeneratedSketch = {
  main: string
  split: { mainFile: string; designsFile: string }
  fileName: string
  designsFileName: string
  sram: SramEstimate
}

export function generate(
  project: Project,
  options: CodegenOptions = NO_PASSES,
): GeneratedSketch {
  const { grid, hardware, speed, frames, groups } = project
  // Only frames actually placed on the timeline reach the sketch.
  const used = playedFrames(frames, groups)
  // Which frames share a table is decided here, before any C is written.
  const plan = planPatterns(used, grid, options)
  const needs = engineNeeds(used, grid, groups)
  const { steps, sequences } = buildSteps(used, groups, grid, plan.names)

  const patterns = emitPlannedPatterns(plan)
  const tables = steps.length > 0 ? emitTables(steps, sequences, needs) : ''

  const name = sketchName(project.name)
  const sections = (withPatterns: boolean) =>
    [
      banner(project, options),
      emitConstants(grid, hardware, speed, options),
      emitTypes(needs),
      ...(withPatterns ? [patterns] : []),
      tables,
      emitSetup(speed),
      emitEngine(grid, hardware, speed, needs, options),
      emitPlayer(needs),
    ]
      .filter((section) => section.trim().length > 0)
      .join('\n\n') + '\n'

  return {
    main: sections(true),
    split: {
      mainFile: sections(false),
      designsFile:
        [`// Pattern data for ${project.name}`, patterns].filter(Boolean).join('\n\n') + '\n',
    },
    fileName: `${name}.ino`,
    designsFileName: 'patterns.ino',
    sram: estimateSram(grid.rows, grid.cols, grid.halfWidth, options),
  }
}

// ---------------------------------------------------------------------------
// Offline memory estimate, for when the compiler bridge isn't running
// ---------------------------------------------------------------------------

/**
 * Refit by scripts/calibrate-flash.mjs against real arduino-cli compiles.
 * With patterns in PROGMEM, Flash is close to linear in stored pattern bytes —
 * unlike the previous code-per-pixel emitter, where avr-gcc collapsed runs of
 * adjacent stores and made the cost sublinear and awkward to predict.
 */
export const FLASH_MODEL = {
  base: 2460,
  perPatternByte: 1.01,
  perStep: 13.4,
  perBandKind: 138,
  /**
   * The second band rotator, paid for only by a timeline that turns bands both
   * ways. Not separately fitted: it is sized like the horizontal rotator it
   * sits beside, which is what one axis already costs.
   */
  bothBandAxes: 138,
  /** Optional engine pieces, emitted only when the timeline uses them. */
  mirrorCost: 100,
  tilingCost: 192,
  holdCost: -186,
}

export const FLASH_TOLERANCE = 0.06

/** Bytes the Arduino core uses beyond the globals we emit. */
export const SRAM_CORE_OVERHEAD = 9

export type MemoryEstimate = {
  sramGlobals: number
  sramStack: number
  flash: number
  flashLow: number
  flashHigh: number
  patternBytes: number
  pixels: number
  designs: number
}

export function estimateMemory(
  project: Project,
  options: CodegenOptions = NO_PASSES,
): MemoryEstimate {
  const { grid, frames, groups } = project
  const used = playedFrames(frames, groups)
  const plan = planPatterns(used, grid, options)
  const { steps } = buildSteps(used, groups, grid, plan.names)

  // frameBuffer + pattern + frameDelayMs (2) + stepStartedAt (4) + the core's 9.
  const patternRam = has(options, 'progmemPatternRead')
    ? PATTERN_DESCRIPTOR_BYTES
    : grid.rows * patternBytes(grid)
  const sramGlobals =
    grid.rows * frameBytes(grid) + patternRam + 2 + 4 + SRAM_CORE_OVERHEAD

  // Shared tables are emitted once, so price the tables rather than the frames.
  let storedBytes = 0
  for (const table of plan.tables) {
    storedBytes += table.rows * (table.bytes[0]?.length ?? 0)
  }

  let pixels = 0
  const sc = sourceCols(grid)
  for (const frame of used) {
    for (let r = 0; r < grid.rows; r++) {
      for (let c = 0; c < sc; c++) if (frame.cells[r * grid.cols + c]) pixels++
    }
  }

  const needs = engineNeeds(used, grid, groups)
  const flash = Math.round(
    FLASH_MODEL.base +
      storedBytes * FLASH_MODEL.perPatternByte +
      steps.length * FLASH_MODEL.perStep +
      needs.bandCounts.length * FLASH_MODEL.perBandKind +
      (needs.bandsHorizontal && needs.bandsVertical ? FLASH_MODEL.bothBandAxes : 0) +
      (needs.mirrorPattern || needs.mirrorFeed ? FLASH_MODEL.mirrorCost : 0) +
      (needs.tiled ? FLASH_MODEL.tilingCost : 0) +
      // A hold-only timeline leaves runScroll() out of the sketch entirely.
      (needs.hold && !needs.scroll ? FLASH_MODEL.holdCost : 0),
  )

  return {
    sramGlobals,
    sramStack: 64,
    flash,
    flashLow: Math.round(flash * (1 - FLASH_TOLERANCE)),
    flashHigh: Math.round(flash * (1 + FLASH_TOLERANCE)),
    patternBytes: storedBytes,
    pixels,
    designs: used.length,
  }
}
