import type { Project } from '../../types'
import { colorRuns, describeColor, normalizeRowColors } from '../colors'
import { sourceCols } from '../grid'
import { assignPatternNames, emitPatterns, packFrame, playedFrames } from './designs'
import { emitConstants, emitEngine, emitSetup, frameBytes, patternBytes } from './engine'
import { buildSteps, emitPlayer, emitTables, emitTypes, engineNeeds } from './loop'

export const BOARD_SRAM = { Uno: 2048, Nano: 2048, Leonardo: 2560, Mega: 8192 } as const

export type SramEstimate = {
  /** frameBuffer + pattern, bit-packed. */
  arrayBytes: number
  fitsUno: boolean
  fitsMega: boolean
  recommendedFree: number
}

export function estimateSram(rows: number, cols: number, halfWidth = false): SramEstimate {
  const patternCols = halfWidth ? Math.floor(cols / 2) : cols
  // One bit per LED: ceil(cols / 8) bytes per row, for each of the two buffers.
  const arrayBytes = rows * Math.ceil(cols / 8) + rows * Math.ceil(patternCols / 8)
  const recommendedFree = 300
  return {
    arrayBytes,
    fitsUno: arrayBytes + recommendedFree <= BOARD_SRAM.Uno,
    fitsMega: arrayBytes + recommendedFree <= BOARD_SRAM.Mega,
    recommendedFree,
  }
}

export function sketchName(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, '_').replace(/^_+|_+$/g, '')
  return cleaned || 'LedPattern'
}

/**
 * The panel is monochrome per LED, so row colours are an assembly note: which
 * LED goes on which row. Only printed when the board is not all one colour.
 */
function colorNote(project: Project): string[] {
  const runs = colorRuns(normalizeRowColors(project.rowColors, project.grid.rows))
  if (runs.length < 2) return []
  return [
    ` *`,
    ` * LED colours fitted per row (row 1 first):`,
    ...runs.map((run) =>
      run.from === run.to
        ? ` *   row ${run.from + 1}: ${describeColor(run.hex)}`
        : ` *   rows ${run.from + 1}-${run.to + 1}: ${describeColor(run.hex)}`,
    ),
  ]
}

function banner(project: Project): string {
  const { rows, cols, halfWidth } = project.grid
  const sram = estimateSram(rows, cols, halfWidth)
  return [
    `/*`,
    ` * ${project.name} — ${rows} x ${cols} LED matrix`,
    ` * Generated by LED Pattern Generator.`,
    ` *`,
    ` * Two 74HC595 chains share one latch: the first shifts ${cols} column bits per row,`,
    ` * the second selects one of ${rows} rows. refreshPanel() multiplexes them.`,
    ` *`,
    ` * Frames are stored one bit per LED and patterns live in PROGMEM, so the two`,
    ` * buffers cost ${sram.arrayBytes} bytes of SRAM${
      sram.fitsUno ? '' : ' — too large for an Uno/Nano (2048 B), use a Mega'
    }.`,
    ...(halfWidth
      ? [` * Patterns are stored ${Math.floor(cols / 2)} columns wide and repeated or mirrored.`]
      : []),
    ...colorNote(project),
    ` */`,
  ].join('\n')
}

export type GeneratedSketch = {
  main: string
  split: { mainFile: string; designsFile: string }
  fileName: string
  designsFileName: string
  sram: SramEstimate
}

export function generate(project: Project): GeneratedSketch {
  const { grid, hardware, frames, groups } = project
  // Only frames actually placed on the timeline reach the sketch.
  const used = playedFrames(frames, groups)
  const names = assignPatternNames(used)
  const needs = engineNeeds(used, grid, groups)
  const { steps, sequences } = buildSteps(used, groups, grid, names)

  const patterns = emitPatterns(used, grid, names)
  const tables = steps.length > 0 ? emitTables(steps, sequences) : ''

  const name = sketchName(project.name)
  const sections = (withPatterns: boolean) =>
    [
      banner(project),
      emitConstants(grid, hardware),
      emitTypes(),
      ...(withPatterns ? [patterns] : []),
      tables,
      emitSetup(hardware),
      emitEngine(grid, hardware, needs),
      emitPlayer(needs),
    ]
      .filter((section) => section.trim().length > 0)
      .join('\n\n') + '\n'

  return {
    main: sections(true),
    split: {
      mainFile: sections(false),
      designsFile:
        [`// Pattern data for ${project.name}`, patterns].filter(Boolean).join('\n\n') + '\n',
    },
    fileName: `${name}.ino`,
    designsFileName: 'patterns.ino',
    sram: estimateSram(grid.rows, grid.cols, grid.halfWidth),
  }
}

// ---------------------------------------------------------------------------
// Offline memory estimate, for when the compiler bridge isn't running
// ---------------------------------------------------------------------------

/**
 * Refit by scripts/calibrate-flash.mjs against real arduino-cli compiles.
 * With patterns in PROGMEM, Flash is close to linear in stored pattern bytes —
 * unlike the previous code-per-pixel emitter, where avr-gcc collapsed runs of
 * adjacent stores and made the cost sublinear and awkward to predict.
 */
export const FLASH_MODEL = {
  base: 2460,
  perPatternByte: 1.01,
  perStep: 13.4,
  perBandKind: 138,
  /** Optional engine pieces, emitted only when the timeline uses them. */
  mirrorCost: 100,
  tilingCost: 192,
  holdCost: -186,
}

export const FLASH_TOLERANCE = 0.06

/** Bytes the Arduino core uses beyond the globals we emit. */
export const SRAM_CORE_OVERHEAD = 9

export type MemoryEstimate = {
  sramGlobals: number
  sramStack: number
  flash: number
  flashLow: number
  flashHigh: number
  patternBytes: number
  pixels: number
  designs: number
}

export function estimateMemory(project: Project): MemoryEstimate {
  const { grid, frames, groups } = project
  const used = playedFrames(frames, groups)
  const { steps } = buildSteps(used, groups, grid, assignPatternNames(used))

  // frameBuffer + pattern + frameDelayMs (2) + stepStartedAt (4) + the core's 9.
  const sramGlobals =
    grid.rows * frameBytes(grid) + grid.rows * patternBytes(grid) + 2 + 4 + SRAM_CORE_OVERHEAD

  let storedBytes = 0
  let pixels = 0
  const sc = sourceCols(grid)
  for (const frame of used) {
    const packed = packFrame(frame, grid)
    storedBytes += packed.rows * (packed.bytes[0]?.length ?? 0)
    for (let r = 0; r < grid.rows; r++) {
      for (let c = 0; c < sc; c++) if (frame.cells[r * grid.cols + c]) pixels++
    }
  }

  const needs = engineNeeds(used, grid, groups)
  const flash = Math.round(
    FLASH_MODEL.base +
      storedBytes * FLASH_MODEL.perPatternByte +
      steps.length * FLASH_MODEL.perStep +
      needs.bandCounts.length * FLASH_MODEL.perBandKind +
      (needs.mirrorPattern || needs.mirrorFeed ? FLASH_MODEL.mirrorCost : 0) +
      (needs.tiled ? FLASH_MODEL.tilingCost : 0) +
      // A hold-only timeline leaves runScroll() out of the sketch entirely.
      (needs.hold && !needs.scroll ? FLASH_MODEL.holdCost : 0),
  )

  return {
    sramGlobals,
    sramStack: 64,
    flash,
    flashLow: Math.round(flash * (1 - FLASH_TOLERANCE)),
    flashHigh: Math.round(flash * (1 + FLASH_TOLERANCE)),
    patternBytes: storedBytes,
    pixels,
    designs: used.length,
  }
}
