export const CONFIG = {
    MATRIX_MIN_ROW_LENGTH:0,
    MATRIX_MIN_COLUMN_LENGTH:0,
    MATRIX_MAX_ROW_LENGTH:100,
    MATRIX_MAX_COLUMN_LENGTH:100,

    MATRIX_GRID_SIZE:25,
    MATRIX_BRUSH_RADIUS:10,
    MATRIX_GRID_COLOR:'#000000',
    MATRIX_CANVAS_BACKGROUND_COLOR:'#ffffff',


    PIXEL_MIN_ROW_LENGTH:0,
    PIXEL_MIN_COLUMN_LENGTH:0,
    PIXEL_MAX_ROW_LENGTH:100,
    PIXEL_MAX_COLUMN_LENGTH:100,

    PIXEL_GRID_SIZE:25,
    PIXEL_BRUSH_RADIUS:10,
    PIXEL_GRID_COLOR:'#ffffff',
    PIXEL_CANVAS_BACKGROUND_COLOR:'#000000'
}